@WebShop.API_HostAddress = https://localhost:7010


GET {{WebShop.API_HostAddress}}/api/users

###

GET {{WebShop.API_HostAddress}}/api/users/1728bf70-3f1f-4e5f-becc-483e0e8a2041

###

POST {{WebShop.API_HostAddress}}/api/users
Content-Type: application/json

{
  "Name": "Proba Test",
  "Email": "test@example.com",
  "Password": "password12345",
  "City": "Beograd",
  "StreetAndNumber": "Knez Mihailova 2",
  "PostalCode": "11000",
  "ContactNumber": "+381641234537"
}


###

DELETE {{WebShop.API_HostAddress}}/api/users/d746dd22-5368-4fe8-dff9-08dc5faf945f

###

PATCH {{WebShop.API_HostAddress}}/api/users/d746dd22-5368-4fe8-dff9-08dc5faf945f
Content-Type: application/json

{
  "Name": "Pathed patch",
  "Password": "patch",
  "ContactNumber": "+381641231537"
}

###

POST {{WebShop.API_HostAddress}}/api/orders
Content-Type: application/json

{
  "userId": "1728bf70-3f1f-4e5f-becc-483e0e8a2041",
  "orderDate": "2024-04-19T10:42:44.545Z",
  "processed": false
}

###
